import { userMention } from "discord.js";
import { QuestT } from "../db/prisma.js";
import { Store } from "../actions/store.js";
import { CustomEmbed } from "./embed.js";
import { commands_details, CommandT } from "./commands.js";

export const quest_details: Record<
  keyof QuestT,
  { description: string; max: number } | undefined
> = {
  donate: { description: "Donate 50K to someone!", max: 1 },
  meme: {
    description: "Post a meme in <#1310737786843824278>",
    max: 1,
  },
  meal: {
    description: "Share your meal in <#1393169480984825896>",
    max: 1,
  },
  pet: {
    description: "Post your pet in <#1310978386688086117>",
    max: 1,
  },
  gamble: { description: "Gamble 25 Times!", max: 25 },
  quote: {
    description: "Share an inspirational quote in <#1387347858835116042>",
    max: 1,
  },
  highlight: {
    description: "Post your highlight in <#1311104580628647939>",
    max: 1,
  },
  cringe_name: {
    description: "Share a weird name in <#1388117861658267718>",
    max: 1,
  },
  art: {
    description: "Show your art skills in <#1310740233117106306>",
    max: 1,
  },
  song: {
    description: "Share a good song in <#1446229960741228647>",
    max: 1,
  },
  count: {
    description: "count 5 times in <#1236751657086484587>",
    max: 5,
  },
  of: undefined,
};

export const emotes = {
  blush: {
    urls: [
      "https://giphy.com/gifs/burn-cameo-oFeUVZfiuim9G",
      "https://giphy.com/gifs/big-sky-aborddelimpala-beau-arlen-RXtBu47mtoETFPiwp0",
      "https://giphy.com/gifs/blushing-disney-bird-VVh7txo37uooM",
      "https://giphy.com/gifs/embarrassed-blush-bashful-QavMUNzmD2HPq",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjFnZjluZTl2ZjI2ejl1aXMxc2c2bzZrdmE3bmVjbDhxeDVydjg3ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/QIXDNqdHT6aQw/giphy.gif",
      "https://giphy.com/gifs/julie-audrey-hepburn-making-me-blush-3o85xHtsgzrusUOA8g",
      "https://giphy.com/gifs/yourreactions-eHpWHuEUxHIre",
      "https://giphy.com/gifs/awkward-embarrassed-blushing-FlHuACrCGXkc0",
      "https://giphy.com/gifs/pokemon-pikachu-blush-hgexLu61GFLr2",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aW1kc2pnNzVzMGQ3b3Nwa2NrZjBjZmF4YmxyOHFoZnBxczE1amtoYSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/PleihcHr0kbJVD0bNe/giphy.gif",
    ],
    titles: [
      "{name} blushed!!",
      "{name} is blushing!",
      "{name}'s face is red~",
      "{name} has turned into a tomato.",
    ],
  },
  cry: {
    urls: [
      "https://giphy.com/gifs/the-office-michael-heartbreak-pynZagVcYxVUk",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcm9pc3p6OGk0eTlnN3Y0cncxNXduY2k5eXpmMDBtem9qMWhyeG81YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/VNTMx3LkpG2anXpwbr/giphy.gif",
      "https://giphy.com/gifs/meme-your-image-mMx7HsHn2l6iQ",
      "https://giphy.com/gifs/spongebob-season-4-spongebob-squarepants-l1AsyjZ8XLd1V7pUk",
      "https://giphy.com/gifs/sad-crying-depressed-fOQs20FLdvINW",
      "https://giphy.com/gifs/disappointed-standing-in-the-rain-Jq7y34Hgfy01y",
      "https://giphy.com/gifs/pout-pouting-poutting-IT8d252aTz13G",
      "https://giphy.com/gifs/wViS9n0RqN2",
      "https://giphy.com/gifs/Zjl3YIB8vXtKg",
    ],
    titles: [
      "{name} is crying... :c",
      "{name} needs a hug...",
      "{name} is crying... there there...",
      "{name} cries... :'c",
    ],
  },
  dance: {
    urls: [
      "https://giphy.com/gifs/nounish-dao-nouns-noggles-tlawNnswcTAmGjKRHQ",
      "https://giphy.com/gifs/page-skills-M5fX8pw9QYBYA",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnhhMW5jYzg0a3V3aXRsaWg0aml3MTNwb3E4YzdkYXI0ZTRsdmpiayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/FbiL9rsmZN3ib2JSGo/giphy.gif",
      "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExd2UzMmdvczJ4ajJ5MjRsMDU2dXd0OXNydWdiY3ljNjFocThhcW10MSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/etOX3h7ApZuDe7Fc5w/giphy.gif",
      "https://giphy.com/gifs/collin-dancing-tupac-2pac-MJs7EYwHyG8XC",
      "https://giphy.com/gifs/soultrain-dancing-soul-train-3ohjVazBFR12PCzk3e",
      "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDUyajA3cWpncnE1MXYwc3E3ejl5aDY3M3ZiZTJjbDFxMHZiNnU2ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l1JohKeoRkY7Oyaje/giphy.gif",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnF6bjA1bzh5aG5lMzV1eDJnM3N3Y2tkcmJ4OTgwdmNsaHl3ODFrbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2XflxzCDmtaPjA0KLZK/giphy.gif",
    ],
    titles: [
      "{name} is dancing!!",
      "{name} loves to dance!",
      "{name} is shaking some booty!!",
    ],
  },
  pout: {
    urls: ["https://giphy.com/gifs/reaction-sad-batman-tajVAagrp6tva"],
    titles: [
      "{name} pouts >:c",
      "{name} is pouting!",
      "{name} doesn't like that!",
    ],
  },
  shrug: {
    urls: [
      "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDJpMXo2amJkaWJ1c2c3aXIzNnNwbWZrOTU1aTBzbHBxd3huMTRrMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jPAdK8Nfzzwt2/giphy.gif",
      "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGt6cXNreHA3eWlxeGhqbGF3eXYzd240b24zazN2ZHdhc2I4a2trMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/y65VoOlimZaus/giphy.gif",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExd3RnMGkxeW45b3R5emNhMW1pNGg3aDBubnE5azdpdGFzd2h1djhjMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/SAHGcjT1jNvDB6oxI8/giphy.gif",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExb2Rud3hwNjA0Nzd4NTY1ZHc1Z29xYng2aXR5cXZvZWN2aGk4dXI2eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/n4FCJYLldGPC95d4ku/giphy.gif",
      "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnRja2NiMjc0bDVndmExY3loNDU0djVhM2p2aGtpbndvdW1rM3owMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/sZEl1yTi26mJzrI4VN/giphy.gif",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExcXpuaG5oeW5oa3gybWZnNWUwMDU3bGVjMG1xcHg2d2RsY3AxMmVnaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ogb8RQdu8zQyc/giphy.gif",
      "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnk2Z2FvbDAzOGs2ZGw1eHV4ajhkY2VsOTBjMzBwMmZpanpmd3VpZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/K6VhXtbgCXqQU/giphy.gif",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZm1ldnVkZ2s4aXVzd2xnNzd5Y2lzYjI2NTB1cndycjY1eTZ2NnJxZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/H3BoxrpcT4fPynU424/giphy.gif",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExYnZkMXhjejB0ZG8wa3hldDc0aXBxaGY4Y2VwcWxzNGw2dHZ3eWRraiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vqKlNf8jpBB7O/giphy.gif",
    ],
    titles: ["{name} shrugs", "{name} doesn't care~", "{name} says, 'o well'"],
  },
  sleepy: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGkydGppeGM4OHFueWRtZDllYnI5OTcyeWc4Zmg0MWZyY256NmJiaCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/bEs40jYsdQjmM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDdxYTQxYm80NTYycDU5bWc0NmNrbXh0NnpqY2VvdmJoODZ2eXV3eiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/YNxvJmicapfWgQUOhi/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cGJieG5lOTYxczZ3OGVocm8wM28weTc0ODNhM2FyMmdjd3lrMGM5byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/neQwaD1vTvaQZsqzRK/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cGJieG5lOTYxczZ3OGVocm8wM28weTc0ODNhM2FyMmdjd3lrMGM5byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o6MblrO4tnPypI4UM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3c3U1NnBrNGZybm1rejRrZmxnZmE5N2N4MzZjdzdzbGYwZHB6end5eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/YGCjALcMdEouipLsYR/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NjZ3N3VhNDY1dGlyc2xlZDJtMXZ5OW9vbjE5eWQ4NTIxaTZybnR0MyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xT0GqBkRFkHno3tOfe/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3c3U1NnBrNGZybm1rejRrZmxnZmE5N2N4MzZjdzdzbGYwZHB6end5eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/NytT69eq5daYcGY5XX/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3c3U1NnBrNGZybm1rejRrZmxnZmE5N2N4MzZjdzdzbGYwZHB6end5eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/z31kxVFwkoeZ33yPS8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3d2dxaXB5YWdtYWJnOGQ1bWsyb2x5N2NlN3EwY2t1dmdjMWdqaDM0byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/DhHRFlvQOWB044Zsm2/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3YzJpb2l2MXE0cTJhczgyd2Mxd2kyN2RnY3N4azNvOW9mY3ZmcnBsayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l0MYw1PU2VmN6kIrC/giphy.gif",
    ],
    titles: [
      "{name} is sleepy...",
      "{name} is tired...",
      "{name} needs a nap...",
      "{name} wants to sleep...",
    ],
  },
  smile: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHAydG4xZ2NmcjVwM2Y4OTdydDMybnNrZ2k3YXVsNXo4NGJsbG03MyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/QTrG6mjkHEkpFR3DqX/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaHAydG4xZ2NmcjVwM2Y4OTdydDMybnNrZ2k3YXVsNXo4NGJsbG03MyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/11ezOCtJ7Eetri/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3YW9lczd5cGJhdGEzOWRheTlsb3p5NTdicGk0MXpsbmFxZjc0MTNiNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aesuRNmaYgcMM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZnBwb3h1NTZhc2VsdDVzZnk4N211eWluOW5ndWplNno2ZTMxM2tueSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/d9A3OAEoPMsSEMcRPy/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Y2FydWMxb3F5YzBkNGg5c3EzYnhmZ2RkYjRwMWE1ZGphY2JiZ3UxdSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LKqDgLlK6SuIM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dmpub2thOHJ3MG83NWEwbzhmOWc5ZTZwbThjN3JpbnRndnpoNHE0OCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o6YglFWW1GHKbNeYo/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dmpub2thOHJ3MG83NWEwbzhmOWc5ZTZwbThjN3JpbnRndnpoNHE0OCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/19sMMhJoxxELS/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3M3plNm9laDJ0NXRhbTYxZHhya3RpZG5wbWxqc2pzM3pmazMxcXA4byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/66uJQnhBgHPnZCErHa/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3M3plNm9laDJ0NXRhbTYxZHhya3RpZG5wbWxqc2pzM3pmazMxcXA4byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/MziKDo6gO7x8A/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MHV6dDh6ZG8yYWh3enA0dmtkNDY0bm5zODUzZno3eDNnOWJtaWNrOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8FVcs24aSuQBpHPg4n/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3VsbnIzbDZ0bGJnYWp4eXI3MXQxM3ZuMWpmdHE5NXI4ajNhbHZoNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/iyhIhjXRqqvGflAkWP/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/hZj44bR9FVI3K/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/0ixAZaU8Gp8R5TdRQT/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/DYH297XiCS2Ck/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ukmZRuEqc2Rbi/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ukmZRuEqc2Rbi/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjhxYmVhaGx1bXJvZmZidThxbjNsejRiaTZ1cmd6bnJjcmQ1dmUzcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Dy6KtvPNfNVAIEx7O6/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2JrbHNsMTBwbm1qcmxzMjdlYXdzb29sd3R0NXhwMWdpMXBzbmJoOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/dvdcBNbAiNVT9Z0iwP/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2JrbHNsMTBwbm1qcmxzMjdlYXdzb29sd3R0NXhwMWdpMXBzbmJoOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/SY2avzeaZ4N7lnbsl8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dzcwMHlmazFrN3Rjcmd1NmgxY2J5aHMzYnJqd3hlOGx3MngwMnRkayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/rjkJD1v80CjYs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cDF3ejVia29jNDZxandrb244aDFyeGt0MGlkZ3dkMWtmd2tmaHo1ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ktABlcyUQIoHmBSlwb/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bW4waTA2aHFhODFzdzZvdmpoZmc0d2EzbnkzNHZ6dzV2NGU0ZmlsZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/soB01mo9e82HmHYfY5/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aW1kc2pnNzVzMGQ3b3Nwa2NrZjBjZmF4YmxyOHFoZnBxczE1amtoYSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/okfvUCpgArv3y/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Z3Z0aDJ2NWV1NjN6bHNpbWZydGt4NGJ1eXhoYnA2OW9vdDVqY3l3eiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UAIg3J4OzepmYxQeAT/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eW14NWxheTB2eDVzdmk5NnVqM20xdWhlNnR0czAzc3IxMHFzY3BsOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/cXblnKXr2BQOaYnTni/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3emh5bmd5Y2M2bW5pbW1nN3ZpYWg3eWZua20xdHVzNHF2YWN6c292bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/HU3kZbOl0DWWI6ulbu/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bG95dGxtaGxjMGhqbHNoMDZ3MjVoZ25ueDIwaTV5aGFyd2NuODdrYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/12mwXD0A6E87L2/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dWIzMXpxaTRyMDV0a2s2MHUzcnlidXkwaXNndW1jeXZoMDJnbWFmMyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/pOeaTGiDBZgYM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3emh5bmd5Y2M2bW5pbW1nN3ZpYWg3eWZua20xdHVzNHF2YWN6c292bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/d7fKljD4WRftoHF031/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MWMwM2ZrbW5oMzZoamZxdjN4cGliYWc1bWdrM2hzdjRoNGhiZWNpayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WYyvz9PIhjLHgiyvR2/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnAxZWtlNXdzZWNyOWZiYWJsaDYzMHB5bmNvdThnajBobjNheWR2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/BYul6RujgoRCryuCdL/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnAxZWtlNXdzZWNyOWZiYWJsaDYzMHB5bmNvdThnajBobjNheWR2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/EoW3jhM6MzsONM15zm/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnAxZWtlNXdzZWNyOWZiYWJsaDYzMHB5bmNvdThnajBobjNheWR2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/B5AVgxf0OzlyE/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnAxZWtlNXdzZWNyOWZiYWJsaDYzMHB5bmNvdThnajBobjNheWR2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/FWAcpJsFT9mvrv0e7a/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnAxZWtlNXdzZWNyOWZiYWJsaDYzMHB5bmNvdThnajBobjNheWR2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3CQA4cPx7UDkY/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bGdjNGt2ZHg5MmhlYzBkNGF0Zmp5cDY0MHI5dHh4b3ZiaGFpaGdrYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/he43oHTj5D008/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3a2pjY2YzeHNocnB4amxuODA4cG85OGZwNjI1ZzZ0cXFnanQzM3BrZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/IifbrS5cNj1ub91I1W/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cHFuMnkxN3l5d2Z1Z3pjbjM4MDQxdzFqdWRvdTY1cWZhbzN1aGxvOCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Wr37JyP3vNhfI57pXU/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MGJ6dmVwcHU3a3R5eXAwZDZ1MjhtaHA3c3hzaTlkeW5sYndld3FqYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/dEFIIniUxS4lKcjVOV/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTEyM2p1bWJiamt5bjFocTlqa3RqcDNlcGRrYTN0ZTRwM2k4c3A3NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LR5GeZFCwDRcpG20PR/giphy.gif",
    ],
    titles: ["{name} smiles! c:", "{name} has a grin!!", "{name} is happy!"],
  },
  smug: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcW5odnpjZ2ZsdXk0bHZ2ZTVuYWNoaDlwbDhrMWN0cnpzdHJoYTJyciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Vff5Qxz6LLzag/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcW5odnpjZ2ZsdXk0bHZ2ZTVuYWNoaDlwbDhrMWN0cnpzdHJoYTJyciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o7TKWineS040erhjq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcW5odnpjZ2ZsdXk0bHZ2ZTVuYWNoaDlwbDhrMWN0cnpzdHJoYTJyciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o7TKWineS040erhjq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cGhieHJjYTVvbWFmeW83ZW1oZnNyM2h2dWJiM2N0MnJnNWhxNXJrdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/JGSCwTt87agIU/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bW84d3cxMXg5OWFkdWx6ejBiaDR6YTRqdWFmMGJhNmtqbzE3ejE5diZlcD12MV9naWZzX3NlYXJjaCZjdD1n/B5G2f8kELLAsp4XVrs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2cxYjcyNzFzbzAzM2pma2pyYW4wbW5mMWVoNHRwczB5NXB4Z3I5dSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aesuRNmaYgcMM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2cxYjcyNzFzbzAzM2pma2pyYW4wbW5mMWVoNHRwczB5NXB4Z3I5dSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/2w5PwZgB7PG67s7O7s/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGhuZnExaXIxY3JvMWNmZ2dldmphdGs4YnA1dzJsOGh1ejkwd21iOSZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/26BRzXPtk1nUiaMxO/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2VsYzVleTcycnNuZGIxeHprbWtvbDlhb2w2bHlwMjh5bWh4eDVjeSZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/r6BjJgDkeQcGA/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2VsYzVleTcycnNuZGIxeHprbWtvbDlhb2w2bHlwMjh5bWh4eDVjeSZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/wkBysf5P5eCOc/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2VsYzVleTcycnNuZGIxeHprbWtvbDlhb2w2bHlwMjh5bWh4eDVjeSZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/fnVWIQYq8mU5853ELt/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dm02dmhpMGxneGs3ZXNoM2Zrc2ZmcnZnd29jeDFrNXRlbXM5aGYxMCZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/BbMJgat91VCeFqCaax/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2N0ZjM1Z3ZoZ3k5OXI1MGh4NmhpZXB5N3BtMjgyd2Fkd3pza2g3cCZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/44b1ABtsG7VTy/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3b2N0ZjM1Z3ZoZ3k5OXI1MGh4NmhpZXB5N3BtMjgyd2Fkd3pza2g3cCZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/xTiTnnNFM62sUuGwNi/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MGNyYzhrOWtvcjMzN2RrYWdtdmY1enk3OWE1dW1tZThjOHB3OGF3aCZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/geJdVv7ByXUnCGdjlh/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NTkwMjVpbHg2aHV2MGVwd3dteGJ5MXNtamdvNzl4cHh5YXVlYWNkYyZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/2UDBcExoz3R08IRpWr/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaXc2ODduNW84Mmpra3dqeDBzejY2eXJmbzk4OG1waW85aTA3bzA0dSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/f6zcJssQkdT4VQ7dIF/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaXc2ODduNW84Mmpra3dqeDBzejY2eXJmbzk4OG1waW85aTA3bzA0dSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/JR6YqHkUsxTX8ozSYh/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bnZ5ODIwb3pycDA5c2RsOXRwZXN6aTZ0enVwZXRkMno2OGt0dXdoZiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/uv7Y6e1tDuiL82Eu1i/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3enZsb3diODZnazV4eDFvamJ5Ynp6Yjk0eXdnZnluYzVrZndzOGl1YiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/XSvmEGj0qqYlW5ueuQ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZGV1dmQ1d2hlNDh4OHl0cmVtNGE5YW5pNDFuc2phaG5kdnozbzhhcSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1XGbq09J7GnQ4uPl1l/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dHR1eWhpaHI5OTlucmMyeTJ3OXlqZWllejFha3o4ajRtczZpcXhudiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WS16R23Miz6P1Bp0C7/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3a3dkeG91ajk1ajF4ZGFlYWM5cDQwdDRxN3JqbnNnM3BwOTdjenNmeiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/u4cGGfRq8Z4BCD3tmU/giphy.gif",
    ],
    titles: [
      "{name} scoffs c:<",
      "{name} has a smug look c;",
      "{name} thinks little of you ;)",
    ],
  },
  thumbsup: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHdvZmFuaTgydzRlbzZ0MjhnNGQxOTNrb3k5ZW02bTJqeXVodHJwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/rMEJyjch7L1tlRlCl3/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHdvZmFuaTgydzRlbzZ0MjhnNGQxOTNrb3k5ZW02bTJqeXVodHJwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8YKstBTN4i68E/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHdvZmFuaTgydzRlbzZ0MjhnNGQxOTNrb3k5ZW02bTJqeXVodHJwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UOkqOjQgp4lIujxa4w/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHdvZmFuaTgydzRlbzZ0MjhnNGQxOTNrb3k5ZW02bTJqeXVodHJwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/btbTjWIQh2WI2Towh5/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHdvZmFuaTgydzRlbzZ0MjhnNGQxOTNrb3k5ZW02bTJqeXVodHJwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/2441Rzq5dCUWoEAeqZ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dWp6Z3dkbGcxbDJmeXJoYmJlbzk3ajB6d2txZ2l3YWYxcG5maWNlYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/9c9tE5Pr0qElW/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MTJpODlobmxyaTVrM3dpczJ6djhzeWZmZXl0d2I2bTFxcTdnOWZ3cSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohs7IyTLZ1lfV64zS/giphy.gif",
    ],
    titles: [
      "{name} gives a thumbs up!",
      "{name} agrees!",
      "{name} has a thumbs up!",
    ],
  },
  thinking: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/a5viI92PAF89q/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/d3mlE7uhX8KFgEmY/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/DfSXiR60W9MVq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WRQBXSCnEFJIuxktnw/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/y3QOvy7xxMwKI/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5XELueHTZd3XCaMGbw/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW1hYzF5Mm0xbzZ2cHR5dHM4cGdydGU2amVxYmhhY2psOHpjZjFncyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o7TKTDn976rzVgky4/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Zmg3emRpamtleWcyMmF4MzM0NnJ2cW9nMXBoMTYyZ2tidnMzam1wMCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/kPtv3UIPrv36cjxqLs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Zmg3emRpamtleWcyMmF4MzM0NnJ2cW9nMXBoMTYyZ2tidnMzam1wMCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/kPtv3UIPrv36cjxqLs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dnlzNGg0ZjRpZHNhZzJ5bzk3M3BvcTgwOTh1MGdtd3p4ZTFnNDdjNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Ogq017TWp45JadcpIK/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dnlzNGg0ZjRpZHNhZzJ5bzk3M3BvcTgwOTh1MGdtd3p4ZTFnNDdjNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Ogq017TWp45JadcpIK/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dnlzNGg0ZjRpZHNhZzJ5bzk3M3BvcTgwOTh1MGdtd3p4ZTFnNDdjNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/TPl5N4Ci49ZQY/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3N3RrbHUwaHh6cTltZ29iNjZneGdhd2lpZzJtMTI2c2d0aGJuaGVrZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/W3a0zO282fuBpsqqyD/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3N3RrbHUwaHh6cTltZ29iNjZneGdhd2lpZzJtMTI2c2d0aGJuaGVrZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/WUwdqYmGaLhP1TVhrL/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTEyM2p1bWJiamt5bjFocTlqa3RqcDNlcGRrYTN0ZTRwM2k4c3A3NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ifQNP4Yr3tCmwbPtB1/giphy.gif",
    ],
    titles: [
      "{name} is thinking...",
      "{name} is trying to understand",
      "{name} cannot process that...",
    ],
  },
  triggered: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/vk7VesvyZEwuI/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/wVcNP3TnXbl84/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/KymorXwDdmvw4/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/pYI1hSqUdcBiw/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/N4hHsZoD3edqw/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/ZMJQEhBskQmQM/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/IG5tmcGU9xenK/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWgxdXA1eWo0bzByenFvbzN5Zmd4M3pnNjl4eGFsdDkwYzA4NHBwNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l3q2K5jinAlChoCLS/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bnl6d3U0dHNjNXJrdTE2ZHU4aW1qeTd4azRsN2hmdDkxMnhzbnVqNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/14tvbepZ8vhU40/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDVxaDE5MmJ0M25lZndtYnJyYzd4dTZvcWxxejJ1cG5iNTQ1MjB4aCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l3978hPCi5iREQk5W/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTEyM2p1bWJiamt5bjFocTlqa3RqcDNlcGRrYTN0ZTRwM2k4c3A3NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/iJxHU0Fo2uMxLlmWgd/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3c3BibDFwajB1bXd3aGZqNGdqMzAyY251b244enF5MGRkY2hpemRveCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/XqrGAfw4Xuro4/giphy.gif",
    ],
    titles: [
      "{name} is triggered!",
      "{name} is TRIGGERED.",
      "{name} is TRIGGERED!!!!",
    ],
  },
  teehee: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExejg2MTMzbWczdTZ4cHpxMno4Mmp4MGNoZndxZno4OTZmcnNzOTVwOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/itMjo4Vjk6d7G/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExejg2MTMzbWczdTZ4cHpxMno4Mmp4MGNoZndxZno4OTZmcnNzOTVwOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8ciLGd6O0d9YXjE5zR/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExejg2MTMzbWczdTZ4cHpxMno4Mmp4MGNoZndxZno4OTZmcnNzOTVwOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/RP3AnZqvnzrY8hlYMk/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MTBzOW14b2U5M3Njd2g0MGV2aXl6YWU0dDVlcWVyeWdlYjF3MHVvbiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UuGtTaLPOAxZnO2vrj/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cWVhdW56b25xYXh1Z2s3NnNyNmFleXM4bXBkbnZpMTFna3BldDc2eCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/R0TLuReCtROToGCuYc/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3VsbnIzbDZ0bGJnYWp4eXI3MXQxM3ZuMWpmdHE5NXI4ajNhbHZoNyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/f8pT7bphqES4M/giphy.gif",
    ],
    titles: ["{name} giggles~", "{name} c;", "{name} ;P"],
  },
  love: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmYxdHd2Mzl0ZWQyMG8yeXp2cWVtdnJ5Y2N4dTN6NDVpMGg1dzA3ZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/f0lS4lOcrGGaAVpxT8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Z2pzaGlnaTZteDZtZW50d2J0MzYzNzlvdmRoODk2eGxienNhcHRuOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1hqb8LwPS2xCNCpWH8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Nzl1MzFncmQxa2lvZWNmYmM2MG9mNjJkNmozcXN5Z2MxNjM0MWRxYyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/R6gvnAxj2ISzJdbA63/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMndnOXdxamZudWg3NGJwd2EwZ3RuY2tlN3R3d2p4ZTc4aGhqeXBmYSZlcD12MV9naWZzX3JlbGF0ZWQmY3Q9Zw/QbQeDAEspJ5oCeGWJk/giphy.gif",
    ],
    titles: ["{name} <3"],
  },
  wink: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cWF4djZyMGE3YzZlbWt1bWd0d2o4Z2IxcXlyamRzemo1MWEydDRtcSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1xHeWqpsUtjm8/giphy.gif",
      "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGRmeDNuOWlpeW9scG1iZzJ1bzh2dzRiNHA1dWd0OXBrMW0xdDI2ZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wrBURfbZmqqXu/giphy.gif",
      "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWhlcW95ZTZ1YWt4ejY1YTkzb21saW1jY2UxNGtpNDFkMm55dXE3YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/10UUe8ZsLnaqwo/giphy.gif",
      "https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWZlaW1nN3AycnAzY3R5eG5oamFta3d3ZzZpZ3h4NGF3aGsyeDJ3YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/dk3TmFZpn6pUI/giphy.gif",
    ],
    titles: ["{name} is winking ;)", "{name} ;)"],
  },
} satisfies EmotesNActionsT;

export const actions = {
  hug: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2V0bGd0cXV3bGI5cGtxN2RyYWFueWtqYzN2NzVocGM5czFnZmJoZiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4CTlTWDNqcBva/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2V0bGd0cXV3bGI5cGtxN2RyYWFueWtqYzN2NzVocGM5czFnZmJoZiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/VduFvPwm3gfGO8duNN/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2V0bGd0cXV3bGI5cGtxN2RyYWFueWtqYzN2NzVocGM5czFnZmJoZiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/42YlR8u9gV5Cw/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3em5zeTRzYXhiMmFibWNibTZ2MnQwd2h5bjl5cDN1c3Q5dGV6dDRmZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/gnXG2hODaCOru/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZTRpaHFzc3Nxcmlza3hrcWs5Mmd3YWpjejJibnkwcmZmank2cHVhaCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/TGjXIOmDhfJFlY5NM5/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NGFod29yMGE1ZDBkcng0cXY5NXp6bWJxNm05MHI5bzFmanZ5ZmZ4ZSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/hRCFBt3ta0DJeGto2R/giphy.gif",
    ],
    titles: [
      "{name} hugs {target}!",
      "{name} gives {target} a big hug!",
      "{name} hugs {target}!! Don't squeeze too hard!",
    ],
  },
  poke: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2c4cm82cGFxcjYzMDBiaWQ5ejFsbWllc3lxb3U5ejE0dDRveHFhZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/jCENc3aA4fLJm/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2c4cm82cGFxcjYzMDBiaWQ5ejFsbWllc3lxb3U5ejE0dDRveHFhZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3x5nIjlszTBQs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2c4cm82cGFxcjYzMDBiaWQ5ejFsbWllc3lxb3U5ejE0dDRveHFhZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/wsUuwZ0pdhUMxvO55c/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2c4cm82cGFxcjYzMDBiaWQ5ejFsbWllc3lxb3U5ejE0dDRveHFhZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/f5GY3rJG60NShta01W/giphy.gif",
    ],
    titles: ["{name} boops {target} .-.", "{name} pokes {target}! boop!"],
  },
  slap: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGZ6OWNpN3Q5Y3YwM2MyejE0bnhncXY2MXpmY2hwdmVxeGxzYnJuNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3XlEk2RxPS1m8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGZ6OWNpN3Q5Y3YwM2MyejE0bnhncXY2MXpmY2hwdmVxeGxzYnJuNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4R6EMXhNPz5WsJFEta/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeGZ6OWNpN3Q5Y3YwM2MyejE0bnhncXY2MXpmY2hwdmVxeGxzYnJuNiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/mEtSQlxqBtWWA/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MnYyZGFzOXAzNHB3ODZkdXE2bndnaTdhazMwMWFndXo3dGdhYmNsYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/60rUVyj8ShyuEhHbaz/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MnYyZGFzOXAzNHB3ODZkdXE2bndnaTdhazMwMWFndXo3dGdhYmNsYiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1zgOyLCRxCmV5G3GFZ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3czkyMTl0YXVqcG1wbmFkb2tqenpqYnh3bGp6NWFtem50cjhtampjdSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6HFUDKwlWcAbC/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NmhoYnVuYnNwZjV6N2Q3a2llNDMxbnJhb3M2Nnl3c256MjVvZHg3MyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l41YtWUr1CGntlR1C/giphy.gif",
    ],
    titles: [
      "{name} slaps {target}!! Deserves it!",
      "{name} slaps {target}!! oof.",
      "{name} slaps {target}!! That looks like it hurt...",
    ],
  },
  stare: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/96DeW8wUdpN96/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/c5FhF1waAJ5wk/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/BIZkwFtu2xDlS/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/FY8c5SKwiNf1EtZKGs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/XF5AnCJV7PCtGwdHNC/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/MVoX99cLXXU0gq7QuG/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8ac9tQi8GtuJaW8HBJ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNG9tYWhqN2NjNGppbmtpZWN0NWlyYmpidmcwMjRxaGxhNHhyYml5eSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Q4ScVMm5oBP44/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NDRyNHltNnpxc2RyNTFqY2YwZWVmbmUwcWRvYTc5MTE0d3phb2luMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/F3BeiZNq6VbDwyxzxF/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NDRyNHltNnpxc2RyNTFqY2YwZWVmbmUwcWRvYTc5MTE0d3phb2luMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/aXUU30cDBa9tVQz37V/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aTg4NnZpcXljMmkydXhpZjk0Nm4zcmhlczJ5dXc4M3pjMGRyaGJ5byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/l0HU3UpYqHp68mK64/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aTg4NnZpcXljMmkydXhpZjk0Nm4zcmhlczJ5dXc4M3pjMGRyaGJ5byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/meJN6qdG74lUKAJTQl/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aTg4NnZpcXljMmkydXhpZjk0Nm4zcmhlczJ5dXc4M3pjMGRyaGJ5byZlcD12MV9naWZzX3NlYXJjaCZjdD1n/9Z7SJLN4UYgGcVZQaJ/giphy.gif",
    ],
    titles: [
      "{name} stares at {target}...",
      "{name} looks directly at {target}'s eyes...",
      "{name} stares at {target}... What did you do??",
    ],
  },
  highfive: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3emhya3pmY2c2ZGtob3o0aTltd3Q5ZjFpaTd1c3NmbzF4em9vcmFmOSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/jRPuK99kwLGIblQfQQ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bWh0aGppZW1xbzZ5ZnVkZHh5OWc2MmtwaTAzZzIyc3dvaHZoemw3YiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/KaYDY4bVN58GELotj4/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eThjenh6dXJpa2prNmI3a2gzc3NxOGdpbTRodGo1Z3NpZGxucnF0ciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/26BRr8WThUKXjIWpq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3OWJiZWZ1eWl0MG4yeDI2aG5qMmRhY24ycGcyMmZ6a2V0ajdlc2FmMCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8zzR3BjbioxdMcodab/giphy.gif",
    ],
    titles: [
      "{name} gives {target} a highfive!",
      "{name} highfives {target}!",
      "{name} highfives {target}! Nice!",
    ],
  },
  greet: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHJseDVjeTltYjd0dmQ5bmFleXpxeXduZ202OTFhM3Vra3NwMWRnMyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xT9IgG50Fb7Mi0prBC/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3aXl5N25wcDk3ZTdjYm9kNzJpNncxdml2c2U1MnFjYnp2a2tvZ3docCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/L2Tc5iTowsRFmpOMb0/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWNjc3Y3c216MDI3Yjh6bjZsNjd0ZmQycDY1am93ZXJzMWd4bHc2ZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LPFNd1AJBoYcVUExmE/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWNjc3Y3c216MDI3Yjh6bjZsNjd0ZmQycDY1am93ZXJzMWd4bHc2ZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6hKL8BI8rRNrMRFtAx/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWNjc3Y3c216MDI3Yjh6bjZsNjd0ZmQycDY1am93ZXJzMWd4bHc2ZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/eoVusT7Pi9ODe/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWNjc3Y3c216MDI3Yjh6bjZsNjd0ZmQycDY1am93ZXJzMWd4bHc2ZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/6yU7IF9L3950A/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3dGwwenZmNTVnYzY4b3VheG0ydXdsbXR1cHJ4azlrenB1eTB2cGZwdSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/oBYB0gqUy3xxBf89aT/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcTVrMTczanUyejJjcHBnc2txb29qa3FlcnlnODRuNndnbnZrY2toNCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/101DNxoBTatF16/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cDIwYnlpbmx0NW82N2hkcnZ4OTQ5ZDg2OHpqemNmNHZkazBmM21hciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/1hPhIFVwHMSaYVQp99/giphy.gif",
    ],
    titles: [
      "{name} says hello to {target}",
      "{name} waves at {target}",
      "{name} says hi to {target}!",
    ],
  },
  punch: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemgxZWJvNGhleGR3MDJ2MnU2bzIxdWVtMGZwODRoYzljMW90Ym1kbyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/SzC42gUrhHopW/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemgxZWJvNGhleGR3MDJ2MnU2bzIxdWVtMGZwODRoYzljMW90Ym1kbyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/d31wMAc5PUktQGpq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemgxZWJvNGhleGR3MDJ2MnU2bzIxdWVtMGZwODRoYzljMW90Ym1kbyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/8ZkfimIBeq8g0A0BUD/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemgxZWJvNGhleGR3MDJ2MnU2bzIxdWVtMGZwODRoYzljMW90Ym1kbyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/Y11Y1zMBIWPIuU8XHn/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemgxZWJvNGhleGR3MDJ2MnU2bzIxdWVtMGZwODRoYzljMW90Ym1kbyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/NY3tXwOBUwQYq7lbXx/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3YnM0ajFubWYzaXQyeW1wNjZiMWkweTUzdzk2M2swbTRkODVvd3FlciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/LPIaOdW7YXoOUTuwRe/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbTIwc2M1cnJ4ZWJwMGNjMW9jZ3l3dmJ4Y3E3OXAzZ2FyZTJ4ZDMydyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/qiiimDJtLj4XK/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbTIwc2M1cnJ4ZWJwMGNjMW9jZ3l3dmJ4Y3E3OXAzZ2FyZTJ4ZDMydyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/RN96CaqhRoRHk4DlLV/giphy.gif",
    ],
    titles: [
      "{name} punches {target}!! Oof",
      "{name} gives {target} a punch! Ouch!",
      "{name} gives {target} a wack! Ha!",
    ],
  },
  handholding: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NHZ6YTl3bnY3dnZuaXZqZHNmZjczNjU2NngwamZpa3NxdXBvbXI4cCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o85xIllHU18SKhY40/giphy.gif",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExa2NtanZ0bm8wOHM4NXNnYjRhbjFvd2FqYnE0eHpqbnB5d2Zlc205eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xTiTnB1aEUVOtf7bQA/giphy.gif",
      "https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZHFsZGpsejNvenB4cmlqcjI2bWgzbmlhdGN2bzR6M2t6emJwN2xzOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8dk3eMHn0Y0Fi/giphy.gif",
    ],
    titles: [
      "{name} holds {target}'s hands, adorable!",
      "{name} grabs {target}'s hands, awww",
    ],
  },
  tickle: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXM4Y2FmMGVuNjVzZGoxNXczdDZ1eXJodDZjbzZ3bjV4N2xyYW01NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3ohuPBnHuElqeTtlkc/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXM4Y2FmMGVuNjVzZGoxNXczdDZ1eXJodDZjbzZ3bjV4N2xyYW01NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7sC5l8ZZKMzXG/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXM4Y2FmMGVuNjVzZGoxNXczdDZ1eXJodDZjbzZ3bjV4N2xyYW01NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/GBHgB17Bd9X3O/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXM4Y2FmMGVuNjVzZGoxNXczdDZ1eXJodDZjbzZ3bjV4N2xyYW01NyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/UIIyMCABbnUAg/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3NXcwaW1wN2dtMHhvbDA3bW9vbW9hYmY1OTl2ZjZsbGw5NTZkczNicyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/vf5RXzqGIWrZu/giphy.gif",
    ],
    titles: [
      "{name} tickles {target}! Ha!",
      "{name} tickles {target}! OwO!",
      "{name} tickles {target}!",
    ],
  },
  kill: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXZjODJxMmh1NnJ1eXVxOGRwcWlmOWEzNWxrZmFtMjV3NnV4cXU0ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/CiZB6WIjaoXYc/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXZjODJxMmh1NnJ1eXVxOGRwcWlmOWEzNWxrZmFtMjV3NnV4cXU0ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/14u6vffnoL7tzq/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ZGJvcHI0aXQybHVoaWFmeWljNGZtM2xvZXkwOXVkeTB6aTJ1N3p6ayZlcD12MV9naWZzX3NlYXJjaCZjdD1n/12zQQNVooHEIGQ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bXU0cGdrcHp3ZW43ZzZlajAzbnJ6bHRocDN3b2syMmpneWx1Y3htcCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/10aY2spcMJPFUk/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3MnN6cDdrOGI5bjZwd25scmthdW9ueHJtbWNvZTk4M25qb2prbG50YiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/4uthremE8sCvJfR2Sa/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cTE1aHo3ZGY2dDA5cTN1cWhtZmhncmN1bzFtZzNxa2Rjc21wODRsMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/7TTgV830a3luvc0FbJ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3cTE1aHo3ZGY2dDA5cTN1cWhtZmhncmN1bzFtZzNxa2Rjc21wODRsMiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/U3sOkA3vL7lFLKYw6I/giphy.gif",
      "https://giphy.com/gifs/sad-meme-igkaipulla-template-tNnvxQmLhRdS5gJ4SQ",
    ],
    titles: [
      "{name} killed {target}! Brutal!",
      "{name} killed {target}! Oh my...",
      "{name} killed {target}! oof!",
    ],
  },
  lick: {
    urls: [
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/12VqfGevHQc2vS/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/agfuIXk2Ht9As/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/11SyC4F2WUFfQQ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/q9ldmTuld2Vbifpp4W/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/K7PCrSotYudyvolITs/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWkyNTd3YXloMXloc2U1aG5kemYwNWp0anozOHJwZ2hjaW9vNGdpdiZlcD12MV9naWZzX3NlYXJjaCZjdD1n/JlVkLKuxRSvLy/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bmxoN3ozeGYzYm9mdzlkdWQ0NTk4dm5yOTByenNydjN2cDZ5dHdjYSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/iO7nHxU0xqkow/giphy.gif",
      "https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXd3Z3hvdWJ0dGVycXNrM3ppcXl2cGdkaDZldXhtenRlcHE2MnhsbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kC5wccHNLWdoJWsUMI/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTdid3g0N2hha3Fvb3RsbHAwYTFnczlsM2V1M21jNzZlem81cnVwciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5Nle87WgNwDbsj3P4Y/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTdid3g0N2hha3Fvb3RsbHAwYTFnczlsM2V1M21jNzZlem81cnVwciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/nzsWN8iSDwSlhCDokc/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTdid3g0N2hha3Fvb3RsbHAwYTFnczlsM2V1M21jNzZlem81cnVwciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/QBwRKyS6vXNfmLF7TR/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNTdid3g0N2hha3Fvb3RsbHAwYTFnczlsM2V1M21jNzZlem81cnVwciZlcD12MV9naWZzX3NlYXJjaCZjdD1n/W3H7yzvQowNSy124C8/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTR4bHRpZmpidDhmZDVia3dyMG5zaG9icWFsMjBkZGE1bGU4cGRqdyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/IsODcceRrNPmvjli1q/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXpxcngxMTlxenZxd3BjMDdxMWlnM2QzbTY3eHoxOWlwOTVwZTVweSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xcnw6F78ETwuQ/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3eG5mbnJlc2RsYTRqZ3AyOGhpYzF5bWh4eHQ3dmgzYnkwMGF0M2s5cCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/twQZemYIce0R6qkXRp/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3N3Rtd2U2bzdkbHBtNHhud2FxOWd1a2ppb29sdDJjYzhmM3hoNjdrNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/MFVXn1fmymn0x8H5XH/giphy.gif",
      "https://lede-admin.dailydot.com/wp-content/uploads/sites/69/2024/04/travis-scott-fish-meme-.jpg",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3enJidHlhOXJma3hnNXVnbzg3NXg2YTg0Z3Y1Mnp1c3l0dnZiN3o5diZlcD12MV9naWZzX3NlYXJjaCZjdD1n/pIKwng0u1RTRx2EzDo/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXIycXFqaTNvZjgzNm53ZnFxaWU1MzFwZDkzbnNmanRhbGVnYzQwZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/diDOx07FacXlQu6MkP/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXIycXFqaTNvZjgzNm53ZnFxaWU1MzFwZDkzbnNmanRhbGVnYzQwZCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/NcrhM3USM6TABpus85/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3Z3pnMTZvZnV3OXUwbjRia2N1dDU3YWNseW1tc3Y2ZDR6ODlxbzI2dCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/xe3AmvAGoQBLIw6Fq9/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3bGIyd25sZW8weXRhNmlsd3cwc2UzaTdqOHlpb3R0a3MzZDQ2eHhjZyZlcD12MV9naWZzX3NlYXJjaCZjdD1n/5hs7ufETBVQZqEPJRh/giphy.gif",
      "https://media.giphy.com/media/v1.Y2lkPWVjZjA1ZTQ3ams5eDhxM2w5ODFwd2dmZGh1MmFwOGl3OXYxdXVpYnNheHRibDh2bCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/3o85xosW6qQsCsZ3Ve/giphy.gif",
    ],
    titles: [
      "Ew! we dont support licking here. heres a random meme instead :)",
    ],
  },
} satisfies EmotesNActionsT;

export const flags: Record<string, string> = {
  ad: "Andorra",
  ae: "United Arab Emirates",
  af: "Afghanistan",
  ag: "Antigua and Barbuda",
  ai: "Anguilla",
  al: "Albania",
  am: "Armenia",
  ao: "Angola",
  aq: "Antarctica",
  ar: "Argentina",
  as: "American Samoa",
  at: "Austria",
  au: "Australia",
  aw: "Aruba",
  ax: "Åland Islands",
  az: "Azerbaijan",
  ba: "Bosnia and Herzegovina",
  bb: "Barbados",
  bd: "Bangladesh",
  be: "Belgium",
  bf: "Burkina Faso",
  bg: "Bulgaria",
  bh: "Bahrain",
  bi: "Burundi",
  bj: "Benin",
  bl: "Saint Barthélemy",
  bm: "Bermuda",
  bn: "Brunei",
  bo: "Bolivia",
  bq: "Caribbean Netherlands",
  br: "Brazil",
  bs: "Bahamas",
  bt: "Bhutan",
  bv: "Bouvet Island",
  bw: "Botswana",
  by: "Belarus",
  bz: "Belize",
  ca: "Canada",
  cc: "Cocos (Keeling) Islands",
  cd: "DR Congo",
  cf: "Central African Republic",
  cg: "Republic of the Congo",
  ch: "Switzerland",
  ci: "Côte d'Ivoire (Ivory Coast)",
  ck: "Cook Islands",
  cl: "Chile",
  cm: "Cameroon",
  cn: "China",
  co: "Colombia",
  cr: "Costa Rica",
  cu: "Cuba",
  cv: "Cape Verde",
  cw: "Curaçao",
  cx: "Christmas Island",
  cy: "Cyprus",
  cz: "Czechia",
  de: "Germany",
  dj: "Djibouti",
  dk: "Denmark",
  dm: "Dominica",
  do: "Dominican Republic",
  dz: "Algeria",
  ec: "Ecuador",
  ee: "Estonia",
  eg: "Egypt",
  eh: "Western Sahara",
  er: "Eritrea",
  es: "Spain",
  et: "Ethiopia",
  eu: "European Union",
  fi: "Finland",
  fj: "Fiji",
  fk: "Falkland Islands",
  fm: "Micronesia",
  fo: "Faroe Islands",
  fr: "France",
  ga: "Gabon",
  gb: "United Kingdom",
  "gb-eng": "England",
  "gb-nir": "Northern Ireland",
  "gb-sct": "Scotland",
  "gb-wls": "Wales",
  gd: "Grenada",
  ge: "Georgia",
  gf: "French Guiana",
  gg: "Guernsey",
  gh: "Ghana",
  gi: "Gibraltar",
  gl: "Greenland",
  gm: "Gambia",
  gn: "Guinea",
  gp: "Guadeloupe",
  gq: "Equatorial Guinea",
  gr: "Greece",
  gs: "South Georgia",
  gt: "Guatemala",
  gu: "Guam",
  gw: "Guinea-Bissau",
  gy: "Guyana",
  hk: "Hong Kong",
  hm: "Heard Island and McDonald Islands",
  hn: "Honduras",
  hr: "Croatia",
  ht: "Haiti",
  hu: "Hungary",
  id: "Indonesia",
  ie: "Ireland",
  il: "Israel",
  im: "Isle of Man",
  in: "India",
  io: "British Indian Ocean Territory",
  iq: "Iraq",
  ir: "Iran",
  is: "Iceland",
  it: "Italy",
  je: "Jersey",
  jm: "Jamaica",
  jo: "Jordan",
  jp: "Japan",
  ke: "Kenya",
  kg: "Kyrgyzstan",
  kh: "Cambodia",
  ki: "Kiribati",
  km: "Comoros",
  kn: "Saint Kitts and Nevis",
  kp: "North Korea",
  kr: "South Korea",
  kw: "Kuwait",
  ky: "Cayman Islands",
  kz: "Kazakhstan",
  la: "Laos",
  lb: "Lebanon",
  lc: "Saint Lucia",
  li: "Liechtenstein",
  lk: "Sri Lanka",
  lr: "Liberia",
  ls: "Lesotho",
  lt: "Lithuania",
  lu: "Luxembourg",
  lv: "Latvia",
  ly: "Libya",
  ma: "Morocco",
  mc: "Monaco",
  md: "Moldova",
  me: "Montenegro",
  mf: "Saint Martin",
  mg: "Madagascar",
  mh: "Marshall Islands",
  mk: "North Macedonia",
  ml: "Mali",
  mm: "Myanmar",
  mn: "Mongolia",
  mo: "Macau",
  mp: "Northern Mariana Islands",
  mq: "Martinique",
  mr: "Mauritania",
  ms: "Montserrat",
  mt: "Malta",
  mu: "Mauritius",
  mv: "Maldives",
  mw: "Malawi",
  mx: "Mexico",
  my: "Malaysia",
  mz: "Mozambique",
  na: "Namibia",
  nc: "New Caledonia",
  ne: "Niger",
  nf: "Norfolk Island",
  ng: "Nigeria",
  ni: "Nicaragua",
  nl: "Netherlands",
  no: "Norway",
  np: "Nepal",
  nr: "Nauru",
  nu: "Niue",
  nz: "New Zealand",
  om: "Oman",
  pa: "Panama",
  pe: "Peru",
  pf: "French Polynesia",
  pg: "Papua New Guinea",
  ph: "Philippines",
  pk: "Pakistan",
  pl: "Poland",
  pm: "Saint Pierre and Miquelon",
  pn: "Pitcairn Islands",
  pr: "Puerto Rico",
  ps: "Palestine",
  pt: "Portugal",
  pw: "Palau",
  py: "Paraguay",
  qa: "Qatar",
  re: "Réunion",
  ro: "Romania",
  rs: "Serbia",
  ru: "Russia",
  rw: "Rwanda",
  sa: "Saudi Arabia",
  sb: "Solomon Islands",
  sc: "Seychelles",
  sd: "Sudan",
  se: "Sweden",
  sg: "Singapore",
  sh: "Saint Helena, Ascension and Tristan da Cunha",
  si: "Slovenia",
  sj: "Svalbard and Jan Mayen",
  sk: "Slovakia",
  sl: "Sierra Leone",
  sm: "San Marino",
  sn: "Senegal",
  so: "Somalia",
  sr: "Suriname",
  ss: "South Sudan",
  st: "São Tomé and Príncipe",
  sv: "El Salvador",
  sx: "Sint Maarten",
  sy: "Syria",
  sz: "Eswatini (Swaziland)",
  tc: "Turks and Caicos Islands",
  td: "Chad",
  tf: "French Southern and Antarctic Lands",
  tg: "Togo",
  th: "Thailand",
  tj: "Tajikistan",
  tk: "Tokelau",
  tl: "Timor-Leste",
  tm: "Turkmenistan",
  tn: "Tunisia",
  to: "Tonga",
  tr: "Turkey",
  tt: "Trinidad and Tobago",
  tv: "Tuvalu",
  tw: "Taiwan",
  tz: "Tanzania",
  ua: "Ukraine",
  ug: "Uganda",
  um: "United States Minor Outlying Islands",
  un: "United Nations",
  us: "United States",
  uy: "Uruguay",
  uz: "Uzbekistan",
  va: "Vatican City (Holy See)",
  vc: "Saint Vincent and the Grenadines",
  ve: "Venezuela",
  vg: "British Virgin Islands",
  vi: "United States Virgin Islands",
  vn: "Vietnam",
  vu: "Vanuatu",
  wf: "Wallis and Futuna",
  ws: "Samoa",
  xk: "Kosovo",
  ye: "Yemen",
  yt: "Mayotte",
  za: "South Africa",
  zm: "Zambia",
  zw: "Zimbabwe",
};

export const items_as_string_option = Array.from(Store.ITEMS)
  .filter(([_, data]) => !!data)
  .map(([id, data]) => ({
    name: data!.name,
    value: id.toString(),
  }));

const command_types: {
  title: string;
  description: string;
  color: number;
  categories: Record<
    string,
    (
      | keyof typeof commands_details
      | keyof typeof emotes
      | keyof typeof actions
    )[]
  >;
}[] = [
  {
    title: "Command List 😁",
    description:
      "Here is a list of all commands, followed by a `/`\n\nFor any questions, please tag a <@&1310967646136565770>",
    color: 0x05b2f7,
    categories: {
      "📹 Streaming": ["schedule", "time-table", "social-media"],
      "🎖️ Ranking": ["net-worth", "superiors"],
      "💸 Economy": [
        "daily",
        "donate",
        "deposit",
        "withdraw",
        "store",
        "buy",
        "give",
        "convert",
      ],
      "🎰 Gambling": [
        "gamble",
        "coinflip",
        "steal",
        "fbi",
        "bribe",
        "hide-n-seek",
        "trivia",
      ],
      // "🌱 Animals": ["zoo", "hunt", "sell", "sacrafice", "lootbox"],
      "🥳 Fun": [
        "8ball",
        "meme",
        "rate",
        "flame",
        "mini-me",
        "wear",
        "inventory",
        "counting-details",
        "trap",
      ],
      "🫂 Social": ["ship", "uwuify"],
      "😃 Emotes": Object.keys(emotes) as (keyof typeof emotes)[],
      "🎬 Actions": Object.keys(actions) as (keyof typeof actions)[],
    },
  },
];

export const help_embeds = [
  ...command_types.map(({ title, description, color, categories }) =>
    new CustomEmbed()
      .setColor(color)
      .setTitle(title)
      .setDescription(description)
      .setFields(
        Object.entries(categories).map(([key, value]) => ({
          name: key,
          value: value.map((el) => `\`${el}\``).join(" "),
        })),
      ),
  ),
  new CustomEmbed()
    .setColor(0xf78b31)
    .setTitle("Actions 🛝")
    .setDescription("Kravan actions besides the commands (tecnologia)")
    .setFields([
      {
        name: "Counting 🔢",
        value:
          "- Whenever u count, u get a coin 🪙\n - If a number is trapped, you can count the next number just normally, or count the trapped number again. If you win, you get 20% of the number to ur pocket. If not, the person who trapped gets 20% and you get public humiliation 😔",
      },
      {
        name: "Reverse 🔙",
        value:
          "You must count in reverse order (pretty straight forward u a dummy if u did not understand)\n\u200b",
        inline: true,
      },
      {
        name: "7 Boom 💥",
        value:
          "If the number you want to count has 7 in it or is a multiplier of 7, you MUST write 'boom' and not the actual number\n\u200b",
        inline: true,
      },
      {
        name: "Leveling 🔼",
        value:
          "Whenever you go up a level, you get 10% of the new level straight to ur pocket 💵",
      },
    ]),

  new CustomEmbed()
    .setColor(0xffffff)
    .setTitle("Creators 🃏")
    .setDescription("(aka created the bot furcefully by ranni)")
    .setFields([
      {
        name: "Coder 💻",
        value: `${userMention(
          "609097048662343700",
        )} (yes guys no AI was used pls appreciate me 🥹🙏)`,
      },
      {
        name: "Masterminds 🧠",
        value: `${userMention("1260205513795174434")} ${userMention(
          "609097048662343700",
        )} ${userMention("133282052350017536")}`,
      },
      {
        name: "Contributers ⛏️",
        value: `${userMention("1260205513795174434")} ${userMention(
          "133282052350017536",
        )} ${userMention("617091659758436516")} (basically gambled too much)`,
      },
    ]),
];
